### ISSUE TITLE
GPU requirement and time consume

### ISSUE THREAD

**Issue by PaulLiuYZ** [chenzhaiyu/polygnn#12]
Hi zhaiyu! 
Congratulations on paper acceptance! 
I wonder the GPU requirement and time consumed for training Polygnn? Is the large dataset time and resource demanding?

**Comment by chenzhaiyu** [comment]
Thanks @PaulLiuYZ. With the default configuration, training takes ~2 days on 4 x A6000 GPUs (150 epochs through 281,571 samples). Since DDP doesn't scale linearly, you should be able to tame the training within a week on a single GPU.

**Comment by PaulLiuYZ** [comment]
Thanks for your reply!
