### ISSUE TITLE
The data preprocessing card doesn't move here, do you know what the reason is?

### ISSUE THREAD

**Issue by ac416** [chenzhaiyu/polygnn#13]
<img width="470" alt="微信图片_20241218232809" src="https://github.com/user-attachments/assets/ce257911-a5af-43a6-b135-2a3903a290d9" />

**Comment by chenzhaiyu** [comment]
Each print statement indicates that a new job has started but has maybe not yet completed. This likely means that all of your CPU cores are currently busy.

**Comment by ac416** [comment]
The problem has been solved, and I changed the multi-process data preprocessing to for loop processing.
