### ISSUE TITLE
Is the dataset open source？

### ISSUE THREAD

**Issue by ac416** [chenzhaiyu/polygnn#3]
Will the later dataset be open source?

**Comment by chenzhaiyu** [comment]
Hi @ac416, the dataset is in our [TODOs](https://github.com/chenzhaiyu/polygnn#todos), please stay tuned :)

**Comment by ac416** [comment]
Thank you very much. I am looking forward to your TODOs

**Comment by chl916185** [comment]
Can you provide a small amount of training data, so that the test code can be run?
@chenzhaiyu

**Comment by chenzhaiyu** [comment]
The [mini dataset](https://github.com/chenzhaiyu/polygnn#quick-start) includes 200 randomly selected samples for quick evaluation. The full Munich dataset, consisting of 291,571 instances, is temporarily accessible [here](https://10.157.147.6/index.php/s/5Kwa8pdj8982XDf) with the access code `PolyGNN2024`. Please note that the dataset requires 332 GB of storage when decompressed.

We are currently working on a permanent storage solution for the dataset. In the meantime, if the temporary link becomes unavailable, feel free to share your email address, and I’ll provide access on a case-by-case basis.
