### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by hcscysh** [chenzhaiyu/polygnn#5]
Since the beginning of this project, I have started to pay attention. The latest release has not updated url_dataset, the default is null. I want to know how to test my own point cloud data. My point cloud data type is .ply.

**Comment by rorrewang** [comment]
@chenzhaiyu Thanks for your excellent work! I just found RANSAC primitive extraction require point cloud normals,but I only have xyz position data.The only way I can think of is to calculate its knn points and get a local normal. Is there any good ways to get point cloud normals?
