### ISSUE TITLE
The normals are wrong

### ISSUE THREAD

**Issue by chl916185** [chenzhaiyu/polygnn#8]
data is DEBY_LOD2_4724226.obj, On the left is the label, on the right is the result of the prediction reconstruction, can you help me analyze it?
![image](https://github.com/user-attachments/assets/af28e968-ca27-4fdf-a231-c1cb59934aec)
@chenzhaiyu

**Comment by chenzhaiyu** [comment]
Face normal consistency isn’t part of PolyGNN, which focuses on polyhedron labeling. You can enforce it via post-processing—[Easy3D](https://github.com/LiangliangNan/Easy3D) has this implemented.

**Comment by chl916185** [comment]
> Face normal consistency isn’t part of PolyGNN, which focuses on polyhedron labeling. You can enforce it via post-processing—[Easy3D](https://github.com/LiangliangNan/Easy3D) has this implemented.

ok, Thank you for your guidance!
